name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: "ubuntu-20.04"
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out source code
        uses: actions/checkout@v1

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "./Dockerfile"
          failure-threshold: warning

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Commit Tag
        id: commit-tag
        run: |
          GIT_SHA=$(git rev-parse --short HEAD)
          echo "::set-output name=tag::${GIT_SHA}"

      - name: Build and Push Commit
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            firefoxx04/site-test-image:latest
            firefoxx04/site-test-image:${{ steps.commit-tag.outputs.tag }}