name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
    - '*'

jobs:
  release:
    name: release
    runs-on: "ubuntu-20.04"
    steps:
      - name: Check out source code
        uses: actions/checkout@v1

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: "./Dockerfile"
          failure-threshold: warning

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Commit Tag
        if: github.ref == 'refs/heads/main'
        id: commit-tag
        run: |
          GIT_SHA=$(git rev-parse --short HEAD)
          echo "::set-output name=tag::${GIT_SHA}"

      - name: Build and Push Commit
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            firefoxx04/site-test-image:latest
            firefoxx04/site-test-image:${{ steps.commit-tag.outputs.tag }}

      - name: Set Release Tag
        if: startsWith(github.ref, 'refs/tags/v')
        id: release-tag
        run: |
          printf '::set-output name=tag::%s' "$(printf '%s' "${{ github.ref }}" | sed 's/refs\/tags\///')"
          echo ${{ steps.commit-tag.outputs.tag }}

      - name: Build and Push Tagged Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            firefoxx04/site-test-image:latest
            firefoxx04/site-test-image:${{ steps.commit-tag.outputs.tag }}